ex03:
	cls
	g++ -Wpedantic -std=c++11 ex03.cpp -o ex03.exe
	@echo Ok
	ex03.exe

ex04:
	cls
	cl /EHsc ex04.cpp
	@echo -------------------------------------
	@echo Ok
	@echo Running
	@echo -------------------------------------
	ex04.exe 