ex03:
	cls
	g++ -Wpedantic -std=c++11 ex03.cpp -o ex03.exe
	@echo Ok
	ex03.exe

ex04:
	cls
	cl /EHsc ex04.cpp
	@echo -------------------------------------
	@echo Ok
	@echo Running
	@echo -------------------------------------
	ex04.exe 

ex05:
	cls
	g++ -Wall -std=c++11 ex05.cpp -o ex05.exe
	@echo -------------------------------------
	@echo Ok
	@echo Running
	@echo -------------------------------------
	ex05.exe 

ex07:
	cls
	g++ -Wall -std=c++11 ex07.cpp -o ex07.exe
	@echo -------------------------------------
	@echo Ok
	@echo Running
	@echo -------------------------------------
	ex07.exe 